name: Mandatory Assignment Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  datetime-function:
    name: Date Time Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run tests
        working-directory: DateTimeFunction
        run: mvn test


  factorial-calculator:
    name: Factorial Calculator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run tests
        working-directory: FactorialCalculator
        run: mvn test


  flooring-mastery:
    name: Flooring Mastery
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run tests
        working-directory: FlooringMastery
        run: mvn test


  school-database:
    name: School Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run tests
        working-directory: SchoolDatabase
        run: mvn test